on:
  #push:
    #branches: main
  schedule:
    #- cron: "*/30 * * * *"   # run every 30 mins
    - cron: "0 */2 * * *"  # run every 2 hrs
    
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr 
            any::jsonlite

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("real feel.R")'

      - name: Commit results
        run: |
          git config --local user.email "ikanx101@gmail.com"
          git config --local user.name "ikanx101"
          git add .
          git commit -m 'Data updated' 
          git push 
